sensor_kit_base_link:

  # lidar
  rs16_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # camera 
  camera_front:
    x: 0.2
    y: 0.1
    z: -0.25
    roll: -1.572
    pitch: -0.017
    yaw: -1.590

  camera1:
    x: 0.0
    y: 0.0
    z: -0.6
    roll: -1.572
    pitch: -0.017
    yaw: -1.590

  # gnss 
  gnss:
    x: 0.0
    y: 0.0
    z: -0.65
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # radar 
  front_radar:
    x: 1.0
    y: 0.0
    z: -1.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rear_radar:
    x: -1.0
    y: 0.0
    z: -1.1
    roll: 0.0
    pitch: 0.0
    yaw: 3.1416
  
  # imu 
  imu_link: 
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0