sensor_kit_base_link:
# camera
  camera_front:
    x: 1.080
    y: 0.173
    z: -0.016
    roll: -1.572
    pitch: -0.017
    yaw: -1.590

  camera_front_right:
    x: 1.080
    y: -0.20
    z: -0.016
    roll: -1.572
    pitch: -0.017
    yaw: -1.590

# combined navigation
  gnss:
    x: -0.37
    y: 0.0
    z: 0.18
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# lidar
  # The laser coordinate system is the y-axis toward the front of the car.
  rs16_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# millimeter wave
  front_radar:
    x: 1.2
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rear_radar:
    x: -1.2
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 3.1416