sensor_kit_base_link:

  # lidar
  rs16_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # camera 
  camera_front:
    x: 0.2
    y: 0.1
    z: -0.25
    roll: -1.572
    pitch: -0.017
    yaw: -1.590

  camera1:
    x: 0.7205965430160353
    y: 0.05197685845037947
    z: -0.5703420555832877
    roll: -1.7447648233046469
    pitch: 0.05137756536867612
    yaw: -1.504080528360984

  # gnss 
  gnss:
    x: 0.0
    y: 0.0
    z: -0.65
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # radar 
  front_radar:
    x: 1.0
    y: 0.0
    z: -1.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rear_radar:
    x: -1.0
    y: 0.0
    z: -1.1
    roll: 0.0
    pitch: 0.0
    yaw: 3.1416
  
  # imu 
  imu_link: 
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0


# sensor_kit_base_link:
# # camera
#   camera_front:
#     x: 0.168
#     y: 0.134
#     z: -0.18
#     roll: 0.0
#     pitch: 0.0
#     yaw: 0.0

#   camera1:
#     x: 0.011
#     y: 0.119
#     z: -0.585
#     roll: 0.0
#     pitch: 0.0
#     yaw: 0.0


# # combined navigation
#   gnss:
#     x: 0.011
#     y: 0.119
#     z: -0.645
#     roll: 0.0
#     pitch: 0.0
#     yaw: 0.0

# #imu
#   tamagawa/imu_raw:
#     x: 0.011
#     y: 0.119
#     z: -0.645
#     roll: 0.0
#     pitch: 0.0
#     yaw: 0.0

# # lidar
#   # The laser coordinate system is the y-axis toward the front of the car.
#   rs16_top_base_link:
#     x: 0.0
#     y: 0.0
#     z: 0.0
#     roll: 0.0
#     pitch: 0.0
#     yaw: 0.0

#   # radar 
#   front_radar:
#     x: 1.0
#     y: 0.0
#     z: -1.1
#     roll: 0.0
#     pitch: 0.0
#     yaw: 0.0
#   rear_radar:
#     x: -1.0
#     y: 0.0
#     z: -1.1
#     roll: 0.0
#     pitch: 0.0
#     yaw: 3.1416